name: .NET Desktop Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore ./Skel2Json.csproj

      - name: Build the project
        run: dotnet build ./Skel2Json.csproj --configuration Release
